### ISSUE TITLE
[Feature Request] React Js Compatibility

### ISSUE THREAD

**Issue by bocodes** [zerodytrash/TikTok-Livestream-Chat-Connector#21]
I am currently trying to create a react js app and wanted to be able to import this library. I have had no luck finding a workaround so maybe a feature request would be the right direction?

**Comment by zerodytrash** [comment]
hi,
this is a Node.js library and can only be used on server side because TikTok does not allow cross origin resource sharing (CORS). The representation via client side components is not part of this libary. Unfortunately I am not familiar with ReactJS. I can only recommend the sample project which offers a client side representation of the data in plain JS:
https://github.com/zerodytrash/TikTok-Chat-Reader

Hope that helps.

**Comment by bocodes** [comment]
Thank you for the reply. The sample project is very helpful. I am having trouble figuring out how to run it locally. Could you instruct me on how to set it up?
